CC=gcc
CFLAGS= -Wall -I./lib
RELEASE_FLAGS= -O2 -DNDEBUG
DEBUG_FLAGS= -ggdb 

SOURCES=$(wildcard lib/*.c)
OBJECTS=$(SOURCES:.c=.o)

BIN=test

.PHONY: all clean prep

all: prep DEBUG

prep:
	@mkdir -p obj

RELEASE: CFLAGS+=$(RELEASE_FLAGS)
RELEASE: $(BIN)

DEBUG: CFLAGS+=$(DEBUG_FLAGS)
DEBUG: $(BIN)

obj/%.o: lib/%.c
	$(CC) $(CFLAGS) -c $< -o $@

$(BIN): $(OBJECTS) test.c
	$(CC) $(CFLAGS) $^ -o $@ 

clean:
	$(RM) -rf $(BIN) obj
